#!/bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom --experimental-backends --backend glx &
$HOME/.config/polybar/launch.sh &
xrdb merge ~/.Xresources &
xrandr --rate 60 &
feh --bg-fill --randomize ~/Pictures/wallpapers/*
wmname LG3D

# workspaces
bspc monitor -d I II III IV V

# windows
bspc config border_width         0
bspc config window_gap          12
bspc config split_ratio          0.6

# cursor
xsetroot -cursor_name left_ptr
